"""empty message

Revision ID: 6024d434f0c7
Revises: 1163d56b2adc
Create Date: 2024-02-20 03:07:36.655392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6024d434f0c7'
down_revision = '1163d56b2adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_medicine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='药材编号'),
    sa.Column('pinyin', sa.String(length=30), nullable=True, comment='药材拼音'),
    sa.Column('chinese', sa.String(length=80), nullable=True, comment='药材中文名'),
    sa.Column('latin', sa.Text(), nullable=True, comment='药材拉丁名'),
    sa.Column('english', sa.Text(), nullable=True, comment='药材英文名'),
    sa.Column('family', sa.String(length=50), nullable=True, comment='科'),
    sa.Column('habitat', sa.Text(), nullable=True, comment='产地'),
    sa.Column('collection_time', sa.Text(), nullable=True, comment='采集时间'),
    sa.Column('use_part', sa.String(length=30), nullable=True, comment='药用部位'),
    sa.Column('efficacy_class', sa.String(length=30), nullable=True, comment='中药材类别（按功效划分）'),
    sa.Column('property', sa.String(length=30), nullable=True, comment='性'),
    sa.Column('flavor', sa.String(length=30), nullable=True, comment='味'),
    sa.Column('meridian_tropism', sa.String(length=50), nullable=True, comment='归经'),
    sa.Column('indications', sa.Text(), nullable=True, comment='功效'),
    sa.Column('appearance', sa.Text(), nullable=True, comment='性状'),
    sa.Column('specification', sa.Text(), nullable=True, comment='规格'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('t_medicine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_medicine_chinese'), ['chinese'], unique=True)
        batch_op.create_index(batch_op.f('ix_t_medicine_pinyin'), ['pinyin'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_medicine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_medicine_pinyin'))
        batch_op.drop_index(batch_op.f('ix_t_medicine_chinese'))

    op.drop_table('t_medicine')
    # ### end Alembic commands ###
